name: git-blame-ignore-revs check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Check that each line in .git-blame-ignore-revs references a commit in the PR branch
      run: |
        ( while read line || [ -n "$line" ]; do
            if ! git branch --contains $line | grep ${GITHUB_REF#*/} > /dev/null
              then
                echo "Line $line in .git-blame-ignore-revs doesn't reference any commit in PR branch"
                exit 1
            fi
          done < .git-blame-ignore-revs )

    - name: Check that each line in .git-blame-ignore-revs references a commit in the main branch
      run: |
        echo "chopped GITHUB_BASE_REF: " ${GITHUB_BASE_REF#*/}
        ( while read line || [ -n "$line" ]; do
            if ! git branch --contains $line | grep ${GITHUB_BASE_REF#*/} > /dev/null
              then
                echo "Line $line in .git-blame-ignore-revs doesn't reference any commit in branch `main`"
                exit 1
            fi
          done < .git-blame-ignore-revs )
