name: .git-blame-ignore-revs check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: each line references a commit
      run: |
        echo $GITHUB_HEAD_REF
        (while read line; echo @line do if ! git branch --contains $line | grep origin/$GITHUB_HEAD_REF; then exit 1; fi; done < .git-blame-ignore-revs )
